// LOCALHOST

GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/644d8fac48a57a41ab7ece74
###
GET http://localhost:8080/contacts/644d902d48a57a41ab7ece75
###
GET http://localhost:8080/contacts/644d908c48a57a41ab7ece76

// PRODUCTION Deploy

###
GET https://lukecse341.onrender.com/contacts
###
GET https://lukecse341.onrender.com/contacts/644d8fac48a57a41ab7ece74
###
GET https://lukecse341.onrender.com/contacts/644d902d48a57a41ab7ece75
###
GET https://lukecse341.onrender.com/contacts/644d908c48a57a41ab7ece76

